import { cookies } from "next/headers";
import { NextRequest } from "next/server";

const BACKEND_URL =
  process.env.BACKEND_URL || process.env.NEXT_PUBLIC_API_ENDPOINT || "";

const MOCK_SYLLABUS = {
  syllabusId: "13245",
  syllabusCode: "CEA201",
  syllabusName:
    "Computer Organization and Architecture_Tổ chức và Kiến trúc máy tính",
  englishName: "Computer Organization and Architecture",
  noCredit: 3,
  degreeLevel: "Bachelor",
  timeAllocation:
    "Study hour (150h) = 45h contact hours + 1h final exam + 104h self-study",
  preRequisite: "None",
  description:
    "This course in an introduction to computer architecture and organization. It will cover topics in both the physical design of the computer (organization) and the logical design of the computer (architecture). The main contents include the organization of a simple stored-program computer: CPU, busses and memory; Instruction sets, machine code, and assembly language; Conventions for assembly language generated by compilers; Floating-point number representation; Hardware organization of simple processors; Address translation and virtual memory; Very introductory examples of input/output devices, interrupt handling and multi-tasking systems.\nChapter covered: Computer Evolution and Performance; A Top-Level View of Computer Function and Interconnection; Cache Memory; Internal Memory; External Memory; Input/Output; Operating System Support; Instruction Sets: Characteristics and Functions; Processor Structure and Function; Reduced Instruction Set Computers; Instruction-Level Parallelism and Superscalar Processors; Parallel Processing; Multicore Computers.",
  studentTasks:
    "- Students must attend at least 80% of contact sessions in order to be accepted to the final examination.\n- Student is responsible to do all exercises and practical given by instructor in class or at home and submit on time. Do quizzes during class.",
  tools: "- Intenet\n- Textbook\n- AI Tools and Simulator software",
  scoringScale: 10,
  decisionNo: "932/QĐ-ĐHFPT dated 08/22/2025",
  isApproved: true,
  note: "",
  minAvgMarkToPass: 5,
  isActive: true,
  approvedDate: "8/22/2025",

  materials: [
    {
      description:
        "Computer Organization and Architecture: Design for Performance",
      author: "William Stallings",
      publisher: "Prentice Hall",
      publishedDate: "2012",
      edition: "9th (or 10th)",
      isbn: "978-0132936330",
      isMainMaterial: true,
      isHardCopy: true,
      isOnline: false,
      note: "",
    },
    {
      description: "Computer architecture : A quantitative approach",
      author: "John L. Hennessy, David A Patterson",
      publisher: "Morgan Kaufmann",
      publishedDate: "",
      edition: "",
      isbn: "",
      isMainMaterial: false,
      isHardCopy: false,
      isOnline: false,
      note: "",
    },
    {
      description:
        "http://williamstallings.com/ComputerOrganization/COA9e-Instructor/",
      author: "",
      publisher: "",
      publishedDate: "",
      edition: "",
      isbn: "",
      isMainMaterial: false,
      isHardCopy: false,
      isOnline: true,
      note: "",
    },
    {
      description:
        "http://williamstallings.com/ComputerOrganization/COA9e-student/",
      author: "",
      publisher: "",
      publishedDate: "",
      edition: "",
      isbn: "",
      isMainMaterial: false,
      isHardCopy: false,
      isOnline: true,
      note: "",
    },
    {
      description:
        "- AI Notes:https://www.https://notegpt.io/ or another AI.\n- Other AI tools: ChatGPT/Copilot/Gamma",
      author: "",
      publisher: "",
      publishedDate: "",
      edition: "",
      isbn: "",
      isMainMaterial: false,
      isHardCopy: false,
      isOnline: true,
      note: "",
    },
    {
      description: "MARIE simulator",
      author: "",
      publisher: "",
      publishedDate: "",
      edition: "",
      isbn: "",
      isMainMaterial: false,
      isHardCopy: false,
      isOnline: false,
      note: "",
    },
    {
      description: "ParaCacheSimulator",
      author: "",
      publisher: "",
      publishedDate: "",
      edition: "",
      isbn: "",
      isMainMaterial: false,
      isHardCopy: false,
      isOnline: false,
      note: "",
    },
  ],

  learningObjectives: [
    {
      name: "CLO1",
      detail:
        "Explain the general functions and structure of a digital computer",
    },
    {
      name: "CLO10",
      detail:
        "Using AI tools and simulator tools to futher explore the main concepts",
    },
    {
      name: "CLO2",
      detail:
        "Present an overview of the evolution of computer technology from early digital computers to the latest microprocessors.",
    },
    {
      name: "CLO3",
      detail:
        "Understand the key performance issues that relate to computer design",
    },
    {
      name: "CLO4",
      detail:
        "Describe in detail the essential elements of computer organisation including internal bus, memory, Input/Output ( I/O) organisations and interfacing standards and discuss how these elements function;",
    },
    {
      name: "CLO5",
      detail:
        "Summarize, at a top level, the key functions of an operating system (OS).",
    },
    {
      name: "CLO6",
      detail:
        "Be able to apply Boolean algebra and digital logic to design and interpret complex digital circuits;",
    },
    {
      name: "CLO7",
      detail:
        "Present various types of addressing modes common in instruction sets, an essential characteristics of machine instructions, types of operands supported by typical machine instruction sets",
    },
    {
      name: "CLO8",
      detail:
        "Explain processor structure and function in details, the operations of Reduced Instruction Set Computers",
    },
    {
      name: "CLO9",
      detail:
        "Investigate, evaluate and communicate general trends in computing technologies such as Instruction-Level Parallelism and Superscalar Processors",
    },
  ],

  sessions: [
    {
      sessionNo: 1,
      topic:
        "- Introduction to the course.\n- Chapter 1: Introduction\n1.1 Organization and Architecture",
      type: "Offline",
      lo: "CLO1, CLO2, CLO10",
      itu: "IT",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "CEA201",
      studentTasks:
        "- Read chapter 1: text book, Slide\n- Use chatGPT(other suilable AI tool) to distinguish between organization and architecture using examples",
      urls: "",
    },
    {
      sessionNo: 2,
      topic: "- Chapter 1: Introduction\n1.2 Structure and Function",
      type: "Offline",
      lo: "CLO1, CLO2, CLO10",
      itu: "T",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "CEA201",
      studentTasks:
        "- Read chapter 1: text book, slide\n- Use chatGPT(other suilable AI tool) to expore main keys: Von Neumann architecture (or Harvard architecture).\n- Use chatGPT to get examples to distinguish structure and function",
      urls: "",
    },
    {
      sessionNo: 3,
      topic:
        "- Chapter 2: Computer Evolution and Performance\n2.1 A Brief History of Computers",
      type: "Offline",
      lo: "CLO1, CLO2, CLO10",
      itu: "T",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "",
      studentTasks:
        "- Read chapter 2 : text book, slide\n- Use chatGPT(other suilable AI tool) to expore the most modern generation of computers is associated with quantum computing, artificial intelligence (AI), and machine learning.",
      urls: "",
    },
    {
      sessionNo: 4,
      topic:
        "- Assessing exercises of chapter 1\n- Chapter 2: Computer Evolution and Performance\n2.2 Designing for Performance",
      type: "Offline",
      lo: "CLO3, CLO10",
      itu: "TU",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "",
      studentTasks:
        '- Read chapter 2 : text book, slide\n- Use ChatGPT to explore about "scalability and performance limits"\n- Presenting exercise chapter 1.',
      urls: "",
    },
    {
      sessionNo: 5,
      topic:
        "- Chapter 2: Computer Evolution and Performance\n2.3 Multicore, MICs, and GPGPUs",
      type: "Offline",
      lo: "CLO3, CLO10",
      itu: "T",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "",
      studentTasks:
        '- Read chapter 2 : text book, slide\n- Use ChatGPT to futher explore about "Thread scheduling and CPU affinity","Distinguish among multicore, MIC, and GPGPU organizations".\n- Use chatGPT to find papers and research papers of NVIDIA',
      urls: "",
    },
    {
      sessionNo: 6,
      topic:
        "- Chapter 2: Computer Evolution and Performance\n2.6 Performance Assessment",
      type: "Offline",
      lo: "CLO3, CLO10",
      itu: "T",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "",
      studentTasks:
        "- Read chapter 2: textbook, slide\n- Ask chatGPT to assess your computer capabilities",
      urls: "",
    },
    {
      sessionNo: 7,
      topic:
        "- Assessing exercises of chapter 2\n- Chapter 3: A Top-Level View of Computer Function and Interconnection\n3.1 Computer Components",
      type: "Offline",
      lo: "CLO4, CLO10",
      itu: "TU",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "",
      studentTasks:
        "- Read chapter 3 : textbook, slide\n- Ask chatGPT to provide steps to build a virtual PC using a any PC building simulator or any activities to simulate the computer's components.\n- Presenting exercise chapter 2.",
      urls: "",
    },
    {
      sessionNo: 8,
      topic:
        "- Chapter 3: A Top-Level View of Computer Function and Interconnection\n3.2 Computer Function",
      type: "Offline",
      lo: "CLO4, CLO10",
      itu: "T",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "",
      studentTasks:
        "- Read chapter 3: textbook, slide\n- Using a any PC building simulator to build a virtual PC or any activities to simulate the computer's components",
      urls: "",
    },
    {
      sessionNo: 9,
      topic:
        "- Chapter 3: A Top-Level View of Computer Function and Interconnection\n3.3 Interconnection Structures",
      type: "Offline",
      lo: "CLO4, CLO10",
      itu: "T",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "",
      studentTasks:
        "- Read chapter 3: textbook, slide\n- Using a any PC building simulator to build a virtual PC or any activities to simulate the computer's components",
      urls: "",
    },
    {
      sessionNo: 10,
      topic:
        "- Chapter 3: A Top-Level View of Computer Function and Interconnection\n3.4 Bus Interconnection",
      type: "Offline",
      lo: "CLO4, CLO10",
      itu: "T",
      studentMaterials: "- Slide\n-Text Book\n- AI tool",
      sDownload: "",
      studentTasks:
        "- Read chapter 3: textbook, slide\n- Using a any PC building simulator to build a virtual PC or any activities to simulate the computer's components",
      urls: "",
    },
  ],

  constructiveQuestions: [
    {
      sessionNo: 1,
      name: "CQ1.1",
      details:
        "What is computer architecture? What is computer organization? Example?",
    },
    {
      sessionNo: 1,
      name: "CQ1.2",
      details:
        "What is the distinction between computer organization and computer architecture?",
    },
    {
      sessionNo: 2,
      name: "CQ1.3",
      details:
        "Explain about Structure of computer. Explain about Functions of computer.",
    },
    {
      sessionNo: 2,
      name: "CQ1.4",
      details:
        "What is the distinction between computer structure and computer function?",
    },
    {
      sessionNo: 3,
      name: "CQ1.5",
      details:
        "Present an overview of the evolution of computer through generations.",
    },
    {
      sessionNo: 4,
      name: "CQ2.1",
      details:
        "List and briefly define some of the techniques used in contemporary processors to increase speed.",
    },
    {
      sessionNo: 4,
      name: "CQ2.2",
      details: "Explain the concept of performance balance.",
    },
    {
      sessionNo: 5,
      name: "CQ2.3",
      details: "Distinguish among multicore, MIC, and GPGPU organizations.",
    },
    { sessionNo: 6, name: "CQ2.4", details: "Explain about System Clock." },
    {
      sessionNo: 6,
      name: "CQ2.5",
      details:
        "Summarize some of the issues in computer performance assessment.",
    },
  ],

  assessments: [
    {
      category: "Assignment",
      type: "on-going",
      part: 2,
      weight: "20.0%",
      completionCriteria: ">0",
      duration: "At home",
      clo: "All CLOs",
      questionType:
        "Option 1: Write a report, or developing assemly program\nOption 2: Follow lecturer's proposal",
      noQuestion:
        "Option 1: build a simple vitrual PC/other suilable activities and a report. Or Develop assemly program\nOption 2: Follow lecturer's proposal",
      knowledgeAndSkill: "Basic computer components/Basic programs",
      gradingGuide: "Teachers assess their works on report",
    },
    {
      category: "Exercices",
      type: "on-going",
      part: 4,
      weight: "40.0%",
      completionCriteria: ">0",
      duration: "Do at home\nPresent in class",
      clo: "All CLOs",
      questionType:
        "Apply AI to answer and explore the content of the subject based on the lecturer's questions and submit the result to Edunext",
      noQuestion: "Follow lecturer's proposal on chapters",
      knowledgeAndSkill: "Studied chapters; knowledge and skills",
      gradingGuide: "Teachers assess their works on report",
    },
    {
      category: "Final exam",
      type: "Final exam",
      part: 1,
      weight: "40.0%",
      completionCriteria: "4",
      duration: "60'",
      clo: "",
      questionType: "Multiple choice",
      noQuestion: "50",
      knowledgeAndSkill:
        "All chapters; knowledge and skills of digital system;",
      gradingGuide: "by Exam board",
    },
  ],

  chapterMaterials: [
    {
      chapterId: "chap-1",
      chapterName: "Chapter 1: Introduction to Computer Architecture",
      blocks: [
        {
          id: "b1",
          type: "H1",
          content: "Introduction to Computer Architecture",
        },
        {
          id: "b1_image",
          type: "IMAGE",
          content:
            "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
        },
        {
          id: "b2",
          type: "PARAGRAPH",
          content:
            "This chapter provides an overview of computer architecture and organization. We will distinguish between these two fundamental concepts and explore the evolution of computer systems.",
        },
        { id: "b3", type: "DIVIDER", content: "" },
        { id: "b4", type: "H2", content: "Architecture vs Organization" },
        {
          id: "b5",
          type: "QUOTE",
          content:
            "Computer architecture refers to those attributes of a system visible to a programmer, whereas computer organization refers to the operational units and their interconnections.",
        },
        {
          id: "b6",
          type: "BULLET_LIST",
          content:
            '["Architecture examples: Instruction set, number of bits used to represent various data types, I/O mechanisms.","Organization examples: Hardware details transparent to the programmer, control signals, interfaces between computer and peripherals."]',
        },
        { id: "b7", type: "H2", content: "Evolution of Computers" },
        {
          id: "b8",
          type: "ORDERED_LIST",
          content:
            '["First Generation: Vacuum Tubes (1946-1957)","Second Generation: Transistors (1958-1964)","Third Generation: Integrated Circuits (1965-1971)","Fourth Generation: Microprocessors (1972-present)"]',
        },
        {
          id: "b8_image",
          type: "IMAGE",
          content:
            "https://images.unsplash.com/photo-1620288627223-53302f4e8c74?auto=format&fit=crop&w=1200&q=80",
        },
        {
          id: "b9",
          type: "CODE_BLOCK",
          content:
            "// Example of a simple assembly instruction\nLOAD R1, 100\nADD R1, R2\nSTORE R1, 200",
        },
        {
          id: "b10",
          type: "TABLE",
          content:
            '[["Generation","Technology","Approximate Dates"],["1","Vacuum tube","1946-1957"],["2","Transistor","1958-1964"],["3","Small/Medium scale integration","1965-1971"],["4","Large scale integration","1972-present"]]',
        },
      ],
    },
    {
      chapterId: "chap-2",
      chapterName: "Chapter 2: Cache Memory and Performance",
      blocks: [
        { id: "c1", type: "H1", content: "Cache Memory System Overview" },
        {
          id: "c1_image",
          type: "IMAGE",
          content:
            "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80",
        },
        {
          id: "c2",
          type: "PARAGRAPH",
          content:
            "Cache memory is designed to combine the memory access time of expensive, high-speed memory combined with the large memory size of less expensive, lower-speed memory.",
        },
        { id: "c3", type: "H2", content: "Cache Principles" },
        {
          id: "c4",
          type: "QUOTE",
          content:
            "The principle of locality of reference dictates that memory references tend to cluster.",
        },
        { id: "c5", type: "DIVIDER", content: "" },
        {
          id: "c6",
          type: "PARAGRAPH",
          content:
            "The basic operation of cache memory involves checking the cache for requested data before accessing main memory. If the data is found, it's a cache hit. If not, it's a cache miss.",
        },
        { id: "c7", type: "H2", content: "Mapping Functions" },
        {
          id: "c8",
          type: "ORDERED_LIST",
          content:
            '["Direct Mapping","Associative Mapping","Set-Associative Mapping"]',
        },
        {
          id: "c9",
          type: "CODE_BLOCK",
          content:
            'def calculate_hit_ratio(hits, misses):\n    total_accesses = hits + misses\n    if total_accesses == 0:\n        return 0.0\n    return (hits / total_accesses) * 100.0\n\nhit_ratio = calculate_hit_ratio(950, 50)\nprint(f"Hit Ratio: {hit_ratio}%")',
        },
      ],
    },
    {
      chapterId: "chap-3",
      chapterName: "Chapter 3: Central Processing Unit (CPU)",
      blocks: [
        {
          id: "d1",
          type: "H1",
          content: "Processor Organization and Function",
        },
        {
          id: "d2",
          type: "PARAGRAPH",
          content:
            "The CPU must fetch instructions, interpret instructions, fetch data, process data, and write data. To do this, it needs a small amount of internal memory called registers.",
        },
        {
          id: "d3",
          type: "IMAGE",
          content:
            "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1200&q=80",
        },
        { id: "d4", type: "H2", content: "Types of Registers" },
        {
          id: "d5",
          type: "BULLET_LIST",
          content:
            '["User-Visible Registers: Enable the machine- or assembly language programmer to minimize main memory references.","Control and Status Registers: Used by the control unit to control the operation of the processor."]',
        },
        {
          id: "d6",
          type: "TABLE",
          content:
            '[["Register Type","Example","Function"],["Data","Accumulator (AC)","Holds operands and results of operations"],["Address","Program Counter (PC)","Contains the address of an instruction to be fetched"],["Status","Program Status Word (PSW)","Contains condition codes and status information"]]',
        },
      ],
    },
  ],
};

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get("sessionToken")?.value;

  // Try real backend first
  try {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (sessionToken) headers.Authorization = `Bearer ${sessionToken}`;

    // Here we query /api/v1/syllabuses/[id] or similar on the real backend
    const res = await fetch(`${BACKEND_URL}/syllabuses/${id}`, {
      headers,
      cache: "no-store",
      signal: AbortSignal.timeout(5000),
    });

    if (res.ok) {
      const data = await res.json();
      return Response.json(data, { status: 200 });
    }
  } catch {
    // Backend unavailable — fall through to mock data
  }

  // Return mock data
  return Response.json({
    status: 200,
    message: "OK (mock data)",
    data: { ...MOCK_SYLLABUS, syllabusId: id },
  });
}
